--1
SELECT LNAME, FNAME
FROM EMPLOYEE
WHERE DNO = 5
AND SSN IN 
    (SELECT ESSN 
    FROM WORKS_ON
    WHERE HOURS > 14
    AND PNO IN
        (SELECT PNUMBER
        FROM PROJECT
        WHERE PNAME = 'ProductX'));
        
--2
SELECT LNAME, FNAME
FROM EMPLOYEE
WHERE EXISTS
    (SELECT * FROM DEPENDENT
    WHERE FNAME = DEPENDENT_NAME 
    AND SSN = ESSN
    AND SEX = 'M');
    
--3
SELECT LNAME, FNAME
FROM EMPLOYEE
WHERE SUPER_SSN IN
    (SELECT SSN FROM EMPLOYEE
    WHERE FNAME = 'Franklin' AND MINIT = 'T' AND LNAME = 'Wong');

--4
SELECT PNAME, PNUMBER, SUM(HOURS)
FROM PROJECT, WORKS_ON
WHERE PNUMBER = PNO
GROUP BY PNAME, PNumber
ORDER BY PNAME;

--5
SELECT LNAME, FNAME
FROM EMPLOYEE
WHERE EXISTS
    (SELECT * FROM WORKS_ON
    WHERE ESSN = SSN);
    
--6
SELECT LNAME, FNAME
FROM EMPLOYEE
WHERE NOT EXISTS
    (SELECT * FROM WORKS_ON
    WHERE ESSN = SSN);
    
--7
SELECT DNAME, DNUMBER, AVG(SALARY)
FROM DEPARTMENT, EMPLOYEE
WHERE DNUMBER = DNO
GROUP BY DNAME, DNUMBER
ORDER BY DNUMBER;

--8
SELECT AVG(SALARY)
FROM EMPLOYEE
WHERE SEX = 'F';

--9
SELECT LNAME
FROM EMPLOYEE
WHERE EXISTS
    (SELECT * FROM DEPARTMENT
    WHERE SSN = MGR_SSN)
AND NOT EXISTS
    (SELECT * FROM DEPENDENT
    WHERE SSN = ESSN);

--10
SELECT AVG(SALARY)
FROM EMPLOYEE
WHERE(SELECT COUNT(*) FROM DEPENDENT
WHERE SSN = ESSN) = 3;

--11
SELECT DNAME, COUNT(*)
FROM DEPARTMENT, EMPLOYEE
WHERE DNUMBER = DNO
GROUP BY DNAME
HAVING AVG(SALARY) > 42000;

--12
SELECT LNAME, FNAME
FROM EMPLOYEE
WHERE DNO = (SELECT DNO FROM EMPLOYEE
                WHERE SALARY = 
                    (SELECT MIN(SALARY) FROM EMPLOYEE));
                    
--13
SELECT LNAME, FNAME
FROM EMPLOYEE
WHERE SUPER_SSN 
IN (SELECT SSN FROM EMPLOYEE WHERE SUPER_SSN = '888665555');

--14
SELECT COUNT(*) AS EMPLOYEE, DNAME
FROM EMPLOYEE
INNER JOIN DEPARTMENT ON EMPLOYEE.DNO = DEPARTMENT.DNUMBER
GROUP BY DEPARTMENT.DNAME;

--15
SELECT FNAME, LNAME, DNO, SALARY
FROM EMPLOYEE
WHERE SALARY > ((SELECT MAX(SALARY) FROM EMPLOYEE E2 WHERE DNO = E2.DNO) - 32000);

--Extra Credit
SELECT LNAME, FNAME, ADDRESS
FROM EMPLOYEE
WHERE EXISTS(SELECT * FROM WORKS_ON, PROJECT
    WHERE SSN = ESSN
    AND PNO = PNUMBER
    AND PLOCATION = 'Houston')
AND
NOT EXISTS(SELECT * FROM DEPT_LOCATIONS
    WHERE DNO = DNUMBER 
    AND DLOCATION = 'Houston');
